import mongoose from 'mongoose';

const carTypeSchema = mongoose.Schema({
    _id: mongoose.Schema.Types.ObjectId,
    lyId: String,
    factory: String,
    brand: String,
    series: String,
    model: String,
    salesName: String,
    year: Number,
    discharge: String,
    type: String,
    price: String,
    salesYear: Number,
    salesMonth: Number,
    productYear: Number,
    unproductYear: Number,
    productStatus: String,
    country: String,
    productFactoryType: String,
    engineType: String,
    airCylinderVolume: String,
    displacement: String,
    inAirType: String,
    oilType: String,
    oilNo: String,
    horsepower: String,
    power: String,
    airCylinderType: String,
    airCylinderNum: String,
    airValveNum: String,
    gearboxType: String,
    gearboxDesc: String,
    gearsNum: String,
    frontBrakingType: String,
    backBrakingType: String,
    helpForceType: String,
    engineLocation: String,
    driveType: String,
    wheelBase: String,
    doorNum: String,
    seatingNum: String,
    frontTyreSpecification: String,
    backTyreSpecification: String,
    frontWheelHubSpecification: String,
    backWheelHubSpecification: String,
    wheelHubMaterials: String,
    backBurnerSpecification: String,
    electricLouver: String,
    fullViewLouver: String,
    xenonHeadlamp: String,
    frontFoglight: String,
    backWindscreenWiper: String,
    air: String,
    autoAir: String,
}, { collection: 'carType'});

const CarType = mongoose.model('carType', carTypeSchema);

export default CarType;